#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSTOwKvdAp1BHzYQ1iKnYg7z4Qsuu0JHz0zB"
APP_SECRET: "kvnVEMgjte+oxG+YLcp3TR+VoKUAaUeW3VdzQF+WKttkBFU9pRWIKL30HeOZjmi+xaP1vVUBIzlauAROXtTXDlIRx8GGor+fQxQd76Ph2EnsIjn8B9/GkmEadfS4rAxWSmJNOCnXaJXrItAkGMu6YE8ALW067frWvOgFIa6gI1NdnxaIY6U="

#계좌번호 앞 8자리
CANO: "63733774"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1100360307957837845/LjzM6H2a7kLSvgNC0fsFJAsMOTzUw0Gn0Nd2xHCilkfRZIrOr7HEG6WRmfFWgDkglW5g"